// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: Kubi.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace Kubi {

  /// <summary>Holder for reflection information generated from Kubi.proto</summary>
  public static partial class KubiReflection {

    #region Descriptor
    /// <summary>File descriptor for Kubi.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static KubiReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "CgpLdWJpLnByb3RvEgRrdWJpImsKBUtOb2RlEhAKCHBrZ190eXBlGAEgASgF",
            "Eg4KBnBrZ19pZBgCIAEoBRILCgN1aWQYAyABKAkSDQoFcm91dGUYBCABKAkS",
            "EAoIZGF0YV9zdHIYBSABKAkSEgoKZGF0YV9ieXRlcxgGIAEoDGIGcHJvdG8z"));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { },
          new pbr::GeneratedClrTypeInfo(null, null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::Kubi.KNode), global::Kubi.KNode.Parser, new[]{ "PkgType", "PkgId", "Uid", "Route", "DataStr", "DataBytes" }, null, null, null, null)
          }));
    }
    #endregion

  }
  #region Messages
  public sealed partial class KNode : pb::IMessage<KNode>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<KNode> _parser = new pb::MessageParser<KNode>(() => new KNode());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<KNode> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Kubi.KubiReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public KNode() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public KNode(KNode other) : this() {
      pkgType_ = other.pkgType_;
      pkgId_ = other.pkgId_;
      uid_ = other.uid_;
      route_ = other.route_;
      dataStr_ = other.dataStr_;
      dataBytes_ = other.dataBytes_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public KNode Clone() {
      return new KNode(this);
    }

    /// <summary>Field number for the "pkg_type" field.</summary>
    public const int PkgTypeFieldNumber = 1;
    private int pkgType_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int PkgType {
      get { return pkgType_; }
      set {
        pkgType_ = value;
      }
    }

    /// <summary>Field number for the "pkg_id" field.</summary>
    public const int PkgIdFieldNumber = 2;
    private int pkgId_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int PkgId {
      get { return pkgId_; }
      set {
        pkgId_ = value;
      }
    }

    /// <summary>Field number for the "uid" field.</summary>
    public const int UidFieldNumber = 3;
    private string uid_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string Uid {
      get { return uid_; }
      set {
        uid_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "route" field.</summary>
    public const int RouteFieldNumber = 4;
    private string route_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string Route {
      get { return route_; }
      set {
        route_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "data_str" field.</summary>
    public const int DataStrFieldNumber = 5;
    private string dataStr_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string DataStr {
      get { return dataStr_; }
      set {
        dataStr_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "data_bytes" field.</summary>
    public const int DataBytesFieldNumber = 6;
    private pb::ByteString dataBytes_ = pb::ByteString.Empty;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public pb::ByteString DataBytes {
      get { return dataBytes_; }
      set {
        dataBytes_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as KNode);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(KNode other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (PkgType != other.PkgType) return false;
      if (PkgId != other.PkgId) return false;
      if (Uid != other.Uid) return false;
      if (Route != other.Route) return false;
      if (DataStr != other.DataStr) return false;
      if (DataBytes != other.DataBytes) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (PkgType != 0) hash ^= PkgType.GetHashCode();
      if (PkgId != 0) hash ^= PkgId.GetHashCode();
      if (Uid.Length != 0) hash ^= Uid.GetHashCode();
      if (Route.Length != 0) hash ^= Route.GetHashCode();
      if (DataStr.Length != 0) hash ^= DataStr.GetHashCode();
      if (DataBytes.Length != 0) hash ^= DataBytes.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (PkgType != 0) {
        output.WriteRawTag(8);
        output.WriteInt32(PkgType);
      }
      if (PkgId != 0) {
        output.WriteRawTag(16);
        output.WriteInt32(PkgId);
      }
      if (Uid.Length != 0) {
        output.WriteRawTag(26);
        output.WriteString(Uid);
      }
      if (Route.Length != 0) {
        output.WriteRawTag(34);
        output.WriteString(Route);
      }
      if (DataStr.Length != 0) {
        output.WriteRawTag(42);
        output.WriteString(DataStr);
      }
      if (DataBytes.Length != 0) {
        output.WriteRawTag(50);
        output.WriteBytes(DataBytes);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (PkgType != 0) {
        output.WriteRawTag(8);
        output.WriteInt32(PkgType);
      }
      if (PkgId != 0) {
        output.WriteRawTag(16);
        output.WriteInt32(PkgId);
      }
      if (Uid.Length != 0) {
        output.WriteRawTag(26);
        output.WriteString(Uid);
      }
      if (Route.Length != 0) {
        output.WriteRawTag(34);
        output.WriteString(Route);
      }
      if (DataStr.Length != 0) {
        output.WriteRawTag(42);
        output.WriteString(DataStr);
      }
      if (DataBytes.Length != 0) {
        output.WriteRawTag(50);
        output.WriteBytes(DataBytes);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (PkgType != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(PkgType);
      }
      if (PkgId != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(PkgId);
      }
      if (Uid.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Uid);
      }
      if (Route.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Route);
      }
      if (DataStr.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(DataStr);
      }
      if (DataBytes.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeBytesSize(DataBytes);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(KNode other) {
      if (other == null) {
        return;
      }
      if (other.PkgType != 0) {
        PkgType = other.PkgType;
      }
      if (other.PkgId != 0) {
        PkgId = other.PkgId;
      }
      if (other.Uid.Length != 0) {
        Uid = other.Uid;
      }
      if (other.Route.Length != 0) {
        Route = other.Route;
      }
      if (other.DataStr.Length != 0) {
        DataStr = other.DataStr;
      }
      if (other.DataBytes.Length != 0) {
        DataBytes = other.DataBytes;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 8: {
            PkgType = input.ReadInt32();
            break;
          }
          case 16: {
            PkgId = input.ReadInt32();
            break;
          }
          case 26: {
            Uid = input.ReadString();
            break;
          }
          case 34: {
            Route = input.ReadString();
            break;
          }
          case 42: {
            DataStr = input.ReadString();
            break;
          }
          case 50: {
            DataBytes = input.ReadBytes();
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 8: {
            PkgType = input.ReadInt32();
            break;
          }
          case 16: {
            PkgId = input.ReadInt32();
            break;
          }
          case 26: {
            Uid = input.ReadString();
            break;
          }
          case 34: {
            Route = input.ReadString();
            break;
          }
          case 42: {
            DataStr = input.ReadString();
            break;
          }
          case 50: {
            DataBytes = input.ReadBytes();
            break;
          }
        }
      }
    }
    #endif

  }

  #endregion

}

#endregion Designer generated code
