# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: Kubi.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\nKubi.proto\x12\x04kubi\"k\n\x05KNode\x12\x10\n\x08pkg_type\x18\x01 \x01(\x05\x12\x0e\n\x06pkg_id\x18\x02 \x01(\x05\x12\x0b\n\x03uid\x18\x03 \x01(\t\x12\r\n\x05route\x18\x04 \x01(\t\x12\x10\n\x08\x64\x61ta_str\x18\x05 \x01(\t\x12\x12\n\ndata_bytes\x18\x06 \x01(\x0c\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'Kubi_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _KNODE._serialized_start=20
  _KNODE._serialized_end=127
# @@protoc_insertion_point(module_scope)
